version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
environment:
  website_name: aspnetcorespa
  website_psw:
    secure: UBm/tZDG4wmtrN6phRaqCBGkZqkpXWIWqMJJFxx6Zknn5imdJssw+9ZZPnT9iriMs364WsFtpNqDi7/sgDt5cQ==
  nodejs_version: "6.9.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - node -e 'console.log(process.env);'
  - cmd: npm test

cache:
  - node_modules -> package.json                                        # local npm modules

before_build:
  # - npm run build:prod                                           # Client production artefacts
  - dotnet restore
build:
  project: AspNetCoreSpa.csproj
  publish_wap: true
  verbosity: quiet
  
after_build:
- cmd: >-
    dotnet publish .\ --output %appveyor_build_folder%\dist

# dotnet publish-iis --publish-folder %appveyor_build_folder%\dist --framework %publish:FullTargetFramework%

artifacts:
- path: dist
  name: web-app

# deploy_script:
# - cmd: '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp=''%appveyor_build_folder%\dist'' -dest:IisApp=''%website_name%'',ComputerName=''https://%website_name%.scm.azurewebsites.net/msdeploy.axd'',UserName=''$%website_name%'',Password=''%website_psw%'',IncludeAcls=''False'',AuthType=''Basic'' -enablerule:AppOffline -retryAttempts:2'
